version: '3.8'

services:
  farm-admin-hybrid:
    container_name: farm-admin-hybrid
    image: supscotty/farmboy:latest
    ports:
      - "5900:5900"   # VNC Server
      - "8080:8080"   # noVNC Web Client
      - "3333:3333"   # Farm Manager Web Interface
      - "2222:22"     # SSH Access
    labels:
      # Core Application Labels
      - "com.farmboy.type=hybrid"
      - "com.farmboy.version=0.2"
      - "com.farmboy.environment=production"
      - "com.farmboy.maintainer=SupScotty"
      # Service Labels
      - "com.farmboy.service.vnc=enabled"
      - "com.farmboy.service.novnc=enabled"
      - "com.farmboy.service.ssh=enabled"
      - "com.farmboy.service.web=enabled"
      # Port Labels
      - "com.farmboy.ports.vnc=5900"
      - "com.farmboy.ports.novnc=8080"
      - "com.farmboy.ports.web=3333"
      - "com.farmboy.ports.ssh=2222"
      # Integration Labels
      - "com.farmboy.integration.dreambot=enabled"
      - "com.farmboy.integration.eternalfarm=enabled"
      - "com.farmboy.integration.discord=enabled"
      # Resource Labels
      - "com.farmboy.resources.memory=2g"
      - "com.farmboy.resources.cpus=2"
      # Database Labels
      - "com.farmboy.database.type=mariadb"
      - "com.farmboy.database.user=farmboy"
      - "com.farmboy.database.host=mariadb"
      - "com.farmboy.database.port=3306"
      - "com.farmboy.database.name=farmboy_db"
      # EternalFarm Service Labels
      - "com.farmboy.eternalfarm.agent.enabled=true"
      - "com.farmboy.eternalfarm.checker.enabled=true"
      - "com.farmboy.eternalfarm.automator.enabled=true"
      - "com.farmboy.eternalfarm.keys.type=individual"
      - "com.farmboy.eternalfarm.services=agent,checker,automator"
      # Auto-login Labels
      - "com.farmboy.autologin=enabled"
      - "com.farmboy.autologin.version=1.0"
      - "com.farmboy.autologin.services=dreambot,agent,checker,automator"
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=mysql://farmboy:Sntioi004!@mariadb:3306/farmboy_db
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
      - DISPLAY=:1
      - VNC_PORT=5900
      - NOVNC_PORT=8080
      - JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64
      # Discord Integration
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1358933950210379816/Pdfyxcilip-xI3-q5ILOl9eRCl0nhEICZHZuvbyQm9aARgzI7GuHQExqBj1NNfkScPvV
      # DreamBot Configuration
      - DREAMBOT_USERNAME=${DREAMBOT_USERNAME:-}
      - DREAMBOT_PASSWORD=${DREAMBOT_PASSWORD:-}
      - DREAMBOT_SCRIPT=${DREAMBOT_SCRIPT:-}
      - DREAMBOT_WORLD=${DREAMBOT_WORLD:-301}
      - DREAMBOT_ARGS=${DREAMBOT_ARGS:---no-splash --developer-mode}
      - DREAMBOT_DIR=/root/DreamBot/BotData
      - DREAMBOT_CLIENT_URL=https://dreambot.org/DBLauncher.jar
      # EternalFarm Configuration
      - ETERNALFARM_AGENT_KEY=P52FE7-I2G19W-C2S4R8-BQZZFP-1FADWV-V3
      - ETERNAL_API_URL=https://api.eternalfarm.net     
      - AUTH_AGENT_KEY=P52FE7-I2G19W-C2S4R8-BQZZFP-1FADWV-V3
      - API_KEY=P52FE7-I2G19W-C2S4R8-BQZZFP-1FADWV-V3
      # Individual EternalFarm service keys (explicitly set)
      - AGENT_KEY=P52FE7-I2G19W-C2S4R8-BQZZFP-1FADWV-V3     
      - CHECKER_KEY=P52FE7-I2G19W-C2S4R8-BQZZFP-1FADWV-V3
      - AUTOMATOR_KEY=P52FE7-I2G19W-C2S4R8-BQZZFP-1FADWV-V3
    volumes:
      - farm_data:/app/data
      - dreambot_data:/root/DreamBot
      # Comment out problematic mounts for now
      # - ./fix-auto-login.sh:/app/fix-auto-login.sh
      # Don't mount these directories to allow container to use the built-in files
      # - ./dashboard-production.html:/app/dashboard-production.html
      # - ./modern-dashboard.css:/app/modern-dashboard.css
      # - ./modern-dashboard.js:/app/modern-dashboard.js
      # - ./style.css:/app/style.css
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - farm-network
    entrypoint: ["/bin/bash", "-c", "chmod +x /app/Entry.sh && /app/Entry.sh"]

  mariadb:
    container_name: farm-admin-mariadb-fresh
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - TZ=Etc/UTC
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
      - MYSQL_ROOT_HOST=%
    volumes:
      - mariadb_data:/config
      # Comment out problematic mounts for now
      # - ./prisma:/prisma
      # - ./setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    ports:
      - "3308:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pSntioi004!"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s
    networks:
      - farm-network
    labels:
      # Core Database Labels
      - "com.farmboy.database.service=mariadb"
      - "com.farmboy.database.type=mariadb" 
      - "com.farmboy.database.version=latest"
      - "com.farmboy.database.provider=linuxserver.io"
      # Configuration Labels
      - "com.farmboy.database.root_host=%" 
      - "com.farmboy.database.default_user=farmboy"
      - "com.farmboy.database.default_db=farmboy_db"
      - "com.farmboy.database.charset=utf8mb4"
      - "com.farmboy.database.collation=utf8mb4_unicode_ci"
      # Security Labels
      - "com.farmboy.database.auth_method=mysql_native_password"
      - "com.farmboy.database.secure_user=farmboy"
      # Health Labels
      - "com.farmboy.database.healthcheck=enabled"
      - "com.farmboy.database.healthcheck.interval=30s"

volumes:
  farm_data:
    driver: local
  dreambot_data:
    driver: local
  mariadb_data:
    driver: local

networks:
  farm-network:
    driver: bridge 