version: '3.8'

services:
  farm-admin-hybrid:
    container_name: farm-admin-hybrid
    image: supscotty/farmboy:latest
    ports:
      - "5900:5900"   # VNC Server
      - "8080:8080"   # noVNC Web Client
      - "3333:3333"   # Farm Manager Web Interface
      - "2222:22"     # SSH Access
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=mysql://root:Sntioi004!@mariadb:3306/farmboy_db
      - DISPLAY=:1
      - VNC_PORT=5900
      - NOVNC_PORT=8080
      - JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64
      # Discord Integration
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1358933950210379816/Pdfyxcilip-xI3-q5ILOl9eRCl0nhEICZHZuvbyQm9aARgzI7GuHQExqBj1NNfkScPvV
      # DreamBot Configuration
      - DREAMBOT_USERNAME=${DREAMBOT_USERNAME:-}
      - DREAMBOT_PASSWORD=${DREAMBOT_PASSWORD:-}
      - DREAMBOT_SCRIPT=${DREAMBOT_SCRIPT:-}
      - DREAMBOT_WORLD=${DREAMBOT_WORLD:-301}
      - DREAMBOT_ARGS=${DREAMBOT_ARGS:---no-splash --developer-mode}
      - DREAMBOT_DIR=/root/DreamBot/BotData
      - DREAMBOT_CLIENT_URL=https://dreambot.org/DBLauncher.jar
      # EternalFarm Configuration
      - ETERNALFARM_AGENT_KEY=P52FE7-I2G19W-C2S4R8-BQZZFP-1FADWV-V3
      - ETERNAL_API_URL=https://api.eternalfarm.net
      - AUTH_AGENT_KEY=P52FE7-I2G19W-C2S4R8-BQZZFP-1FADWV-V3
      - API_KEY=RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5
    volumes:
      - farm_data:/app/data
      - dreambot_data:/root/DreamBot
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - farm-network

  mariadb:
    container_name: farm-admin-mariadb-fresh
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - TZ=Etc/UTC
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
    volumes:
      - /mnt/user/appdata/mariadb-fresh:/config
    ports:
      - "3308:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pSntioi004!"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s
    networks:
      - farm-network

volumes:
  farm_data:
    driver: local
  dreambot_data:
    driver: local

networks:
  farm-network:
    driver: bridge 