version: '3.8'

services:
  farm-admin:
    image: supscotty/farmboy:latest
    ports:
      - "5900:5900"   # VNC Server
      - "8080:8080"   # noVNC Web Client
      - "3333:3333"   # Farm Manager Web Interface
      - "2222:22"     # SSH Access
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=mysql://farmboy:Sntioi004!@mariadb:3306/farmboy_db
      # API Key for EternalFarm services - REPLACE WITH YOUR KEY
      - API_KEY=YOUR_API_KEY_HERE
      - ETERNALFARM_AGENT_KEY=YOUR_API_KEY_HERE
      # DreamBot Configuration (if using DreamBot)
      - DREAMBOT_USERNAME=YOUR_DREAMBOT_USERNAME
      - DREAMBOT_PASSWORD=YOUR_DREAMBOT_PASSWORD
      # Discord Webhook (optional)
      - DISCORD_WEBHOOK_URL=YOUR_DISCORD_WEBHOOK_URL
      # Display settings for VNC
      - DISPLAY=:1
    volumes:
      - farm_data:/app/data
      - dreambot_data:/root/DreamBot
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - farm-network
    labels:
      - "com.farmboy.type=hybrid"
      - "com.farmboy.environment=production"
      - "com.farmboy.autologin=enabled"
      - "com.farmboy.autologin.services=dreambot,agent,checker,automator"

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - TZ=Etc/UTC
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
    volumes:
      - mariadb_data:/config
      - ./prisma:/prisma
      - ./setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pSntioi004!"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s
    networks:
      - farm-network

volumes:
  farm_data:
  dreambot_data:
  mariadb_data:

networks:
  farm-network:
    driver: bridge 