version: '3.8'

services:
  farm-admin:
    image: supscotty/farmboy:latest
    container_name: farm-admin
    restart: unless-stopped
    ports:
      - "3333:3333"
      - "5900:5900"
      - "8080:8080"
      - "2222:22"
    environment:
      NODE_ENV: "production"
      PORT: "3333"
      DATABASE_URL: "mysql://farmboy:Sntioi004!@mariadb:3306/farmboy_db"
      API_KEY: "RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5"
      ETERNALFARM_AGENT_KEY: "RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5"
      ETERNAL_API_URL: "https://api.eternalfarm.net"
      ETERNAL_FARM_KEY: ""
      ETERNAL_AUTH_KEY: ""
      DISPLAY: ":1"
      DISCORD_WEBHOOK_URL: ""
    volumes:
      - farm_data:/app/data
      - dreambot_data:/root/DreamBot
    depends_on:
      - mariadb
    networks:
      - farm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: farm-admin-mariadb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - TZ=Etc/UTC
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
    volumes:
      - mariadb_data:/config
    ports:
      - "3307:3306"
    networks:
      - farm-network

volumes:
  farm_data:
  dreambot_data:
  mariadb_data:

networks:
  farm-network:
    driver: bridge 