version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: farm-admin-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=qQgc^pS0yqZ6SrJm$fKU
      - MYSQL_DATABASE=farmmanager
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - farm-network
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-file-per-table=1
      - --skip-innodb-doublewrite
      - --max_connections=1000
      - --wait_timeout=28800

  farm-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farm-admin
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5900:5900"
      - "8080:8080"
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      DATABASE_URL: "mysql://root:qQgc^pS0yqZ6SrJm$fKU@mariadb:3306/farmmanager?connection_limit=5"
      ETERNALFARM_AGENT_KEY: "P52FE7-I2G19W-C2S4R8-BQZZFP-1FADWV-V3"
      ETERNAL_API_URL: "https://api.eternalfarm.net"
      DISPLAY: ":1"
      DISCORD_WEBHOOK_URL: "${DISCORD_WEBHOOK_URL}"
    volumes:
      - farm_data:/app/data
      - dreambot_data:/root/DreamBot
    depends_on:
      - mariadb
    networks:
      - farm-network
    command: >
      sh -c "
        echo '⏳ Waiting for database...' &&
        while ! mysqladmin ping -h mariadb -u root -p'qQgc^pS0yqZ6SrJm$fKU' --silent; do
          sleep 1
        done &&
        echo '✅ Database is ready!' &&
        cd /app &&
        echo '🔄 Running Prisma migrations...' &&
        npx prisma migrate deploy &&
        echo '🔧 Generating Prisma client...' &&
        npx prisma generate &&
        echo '🚀 Starting application...' &&
        node server.js
      "

volumes:
  farm_data:
    driver: local
  dreambot_data:
    driver: local
  mariadb_data:
    driver: local

networks:
  farm-network:
    driver: bridge 