version: '3.8'

services:
  farm-admin:
    image: supscotty/farmboy:latest
    ports:
      - "5900:5900"   # VNC Server
      - "8080:8080"   # noVNC Web Client
      - "3333:3333"   # Farm Manager Web Interface
      - "2222:22"     # SSH Access
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=mysql://farmboy:Sntioi004!@mariadb:3306/farmboy_db
      - API_KEY=RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5
      - ETERNALFARM_AGENT_KEY=RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5
      # DreamBot Configuration for Bot Launching
      - DREAMBOT_USERNAME=${DREAMBOT_USERNAME:-}
      - DREAMBOT_PASSWORD=${DREAMBOT_PASSWORD:-}
      - DREAMBOT_SCRIPT=${DREAMBOT_SCRIPT:-}
      - DREAMBOT_WORLD=${DREAMBOT_WORLD:-301}
      - DREAMBOT_ARGS=${DREAMBOT_ARGS:---no-splash --developer-mode}
      - DREAMBOT_DIR=/root/DreamBot/BotData
      - DREAMBOT_CLIENT_PATH=/root/DreamBot/BotData/client.jar
      - DREAMBOT_CLIENT_URL=https://dreambot.org/DBLauncher.jar
      # Legacy DreamBot variables (for backward compatibility)
      - DREAMBOT_USER=${DREAMBOT_USER:-}
      - DREAMBOT_PASS=${DREAMBOT_PASS:-}
      # Proxy Configuration
      - PROXY_HOST=${PROXY_HOST:-}
      - PROXY_PORT=${PROXY_PORT:-}
      - PROXY_USER=${PROXY_USER:-}
      - PROXY_PASS=${PROXY_PASS:-}
      # DreamBot Dynamic Settings Configuration
      - DREAMBOT_CPU_SAVER=${DREAMBOT_CPU_SAVER:-true}
      - DREAMBOT_FPS=${DREAMBOT_FPS:-20}
      - DREAMBOT_RENDER_DISTANCE=${DREAMBOT_RENDER_DISTANCE:-25}
      - DREAMBOT_LOW_MEMORY=${DREAMBOT_LOW_MEMORY:-false}
      - DREAMBOT_LOW_DETAIL=${DREAMBOT_LOW_DETAIL:-false}
      - DREAMBOT_MOUSE_SPEED=${DREAMBOT_MOUSE_SPEED:-100}
      - DREAMBOT_USE_RANDOM_WORLD=${DREAMBOT_USE_RANDOM_WORLD:-true}
      - DREAMBOT_USE_CUSTOM_WORLD=${DREAMBOT_USE_CUSTOM_WORLD:-false}
      - DREAMBOT_WORLD=${DREAMBOT_WORLD:--8}
      - DREAMBOT_DEVELOPER_MODE=${DREAMBOT_DEVELOPER_MODE:-false}
      - DREAMBOT_FRESH_START=${DREAMBOT_FRESH_START:-false}
      - DREAMBOT_DISABLE_SECURITY_MANAGER=${DREAMBOT_DISABLE_SECURITY_MANAGER:-false}
      - DREAMBOT_COVERT_MODE=${DREAMBOT_COVERT_MODE:-true}
      - DREAMBOT_SDN_INTEGRATION=${DREAMBOT_SDN_INTEGRATION:-true}
      - DREAMBOT_AUTO_ADD_ACCOUNTS=${DREAMBOT_AUTO_ADD_ACCOUNTS:-true}
      - DREAMBOT_DRAW_SCRIPT_PAINT=${DREAMBOT_DRAW_SCRIPT_PAINT:-true}
      - DREAMBOT_CLIENT_RENDERING=${DREAMBOT_CLIENT_RENDERING:-false}
      - DREAMBOT_DISABLE_SOUNDS=${DREAMBOT_DISABLE_SOUNDS:-true}
      - DREAMBOT_DISABLE_ANIMATION=${DREAMBOT_DISABLE_ANIMATION:-false}
      - DREAMBOT_ROOF_SOLVER_ACTIVE=${DREAMBOT_ROOF_SOLVER_ACTIVE:-true}
      - DREAMBOT_DISMISS_SOLVERS_ACTIVE=${DREAMBOT_DISMISS_SOLVERS_ACTIVE:-true}
      - DREAMBOT_NOTIFY_ON_BAN=${DREAMBOT_NOTIFY_ON_BAN:-true}
      - DREAMBOT_NOTIFY_ON_DEATH=${DREAMBOT_NOTIFY_ON_DEATH:-true}
      - DREAMBOT_NOTIFY_ON_LEVEL_UP=${DREAMBOT_NOTIFY_ON_LEVEL_UP:-true}
      - DREAMBOT_NOTIFY_ON_LEVEL_UP_AMOUNT=${DREAMBOT_NOTIFY_ON_LEVEL_UP_AMOUNT:-5}
      - DREAMBOT_NOTIFY_ON_PET=${DREAMBOT_NOTIFY_ON_PET:-true}
      - DREAMBOT_NOTIFY_ON_VALUABLE_DROP=${DREAMBOT_NOTIFY_ON_VALUABLE_DROP:-true}
      - DREAMBOT_NOTIFY_ON_VALUABLE_DROP_AMOUNT=${DREAMBOT_NOTIFY_ON_VALUABLE_DROP_AMOUNT:-250000}
      - DREAMBOT_NOTIFY_ON_UNTRADEABLE_DROP=${DREAMBOT_NOTIFY_ON_UNTRADEABLE_DROP:-true}
      - DREAMBOT_SCRIPT_WEBHOOK_ACCESS_ALLOWED=${DREAMBOT_SCRIPT_WEBHOOK_ACCESS_ALLOWED:-true}
      - DREAMBOT_MENTION_ON_BAN=${DREAMBOT_MENTION_ON_BAN:-true}
      - DREAMBOT_LAST_RAN_SCRIPT=${DREAMBOT_LAST_RAN_SCRIPT:-Premium:1.312:P2P Master AI}
      - DREAMBOT_FAVORITE_SCRIPTS=${DREAMBOT_FAVORITE_SCRIPTS:-P2P Master AI,# NMZ,Dreamy AIO Skiller Elite Lifetime,Guester - Lifetime}
      - DREAMBOT_LAST_CANVAS_SIZE=${DREAMBOT_LAST_CANVAS_SIZE:-765:503}
      - DREAMBOT_GAME_LAYOUT=${DREAMBOT_GAME_LAYOUT:-Force resizable (modern)}
      - DREAMBOT_STOPS_AFTER_UPDATES=${DREAMBOT_STOPS_AFTER_UPDATES:-true}
      - DREAMBOT_SETTINGS_VERSION=${DREAMBOT_SETTINGS_VERSION:-3}
      # EternalFarm Individual Service Keys
      - AGENT_KEY=${AGENT_KEY:-RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5}
      - CHECKER_KEY=${CHECKER_KEY:-RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5}
      - AUTOMATOR_KEY=${AUTOMATOR_KEY:-RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5}
      - ETERNAL_API_URL=https://api.eternalfarm.net
      - ETERNAL_FARM_KEY=${ETERNAL_FARM_KEY:-}
      - ETERNAL_AUTH_KEY=${ETERNAL_AUTH_KEY:-}
      - DISPLAY=:1
      - JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
    volumes:
      - farm_data:/app/data
      - dreambot_data:/root/DreamBot
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - farm-network
    entrypoint: ["/bin/bash", "-c", "chmod +x /app/Entry.sh && echo '#!/bin/bash\nset -e\n\n# Create fix-auto-login.sh script\ncat > /app/fix-auto-login.sh << \"EOF\"\n$$(cat /fix-auto-login)\nEOF\nchmod +x /app/fix-auto-login.sh\n\n# Run Entry.sh\n/app/Entry.sh' > /tmp/entrypoint.sh && chmod +x /tmp/entrypoint.sh && /tmp/entrypoint.sh"]
    configs:
      - source: fix-auto-login
        target: /fix-auto-login
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Core Application Labels
      - "com.farmboy.type=hybrid"
      - "com.farmboy.version=0.2"
      - "com.farmboy.environment=production"
      - "com.farmboy.maintainer=SupScotty"
      # Service Labels
      - "com.farmboy.service.vnc=enabled"
      - "com.farmboy.service.novnc=enabled"
      - "com.farmboy.service.ssh=enabled"
      - "com.farmboy.service.web=enabled"
      # Port Labels
      - "com.farmboy.ports.vnc=5900"
      - "com.farmboy.ports.novnc=8080"
      - "com.farmboy.ports.web=3333"
      - "com.farmboy.ports.ssh=2222"
      # Integration Labels
      - "com.farmboy.integration.dreambot=enabled"
      - "com.farmboy.integration.eternalfarm=enabled"
      - "com.farmboy.integration.discord=enabled"
      # Resource Labels
      - "com.farmboy.resources.memory=2g"
      - "com.farmboy.resources.cpus=2"
      # Traefik Labels
      - "traefik.enable=true"
      - "traefik.http.routers.farm-admin.rule=Host(`farm-admin.local`)"
      - "traefik.http.services.farm-admin.loadbalancer.server.port=3333"
      # EternalFarm Service Labels
      - "com.farmboy.eternalfarm.agent.enabled=true"
      - "com.farmboy.eternalfarm.checker.enabled=true"
      - "com.farmboy.eternalfarm.automator.enabled=true"
      - "com.farmboy.eternalfarm.keys.type=individual"
      - "com.farmboy.eternalfarm.services=agent,checker,automator"

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - TZ=Etc/UTC
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
    volumes:
      - mariadb_data:/config
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - farm-network

volumes:
  farm_data:
  dreambot_data:
  mariadb_data:

networks:
  farm-network:
    driver: bridge

configs:
  fix-auto-login:
    content: |
      #!/bin/bash
      set -e

      echo "ðŸ”§ Fix Auto-Login Script for EternalFarm and DreamBot"
      echo "==================================================="

      # Create necessary directories
      mkdir -p /appdata/DreamBot/BotData

      # Copy DreamBot settings.json to both locations to ensure it's found
      echo "ðŸ“ Copying DreamBot settings to all potential locations..."
      cp /root/DreamBot/BotData/settings.json /appdata/DreamBot/BotData/settings.json
      chmod 600 /appdata/DreamBot/BotData/settings.json

      # Create agent config to auto-login
      echo "ðŸ“ Creating EternalFarm Agent auto-login config..."
      mkdir -p /root/.eternalfarm
      cat > /root/.eternalfarm/agent.config << EOF
      {
        "key_path": "/appdata/EternalFarm/agent.key",
        "remember_key": true,
        "auto_login": true
      }
      EOF
      chmod 600 /root/.eternalfarm/agent.config

      # Create checker config to auto-login
      echo "ðŸ“ Creating EternalFarm Checker auto-login config..."
      cat > /root/.eternalfarm/checker.config << EOF
      {
        "key_path": "/appdata/EternalFarm/checker.key",
        "remember_key": true,
        "auto_login": true
      }
      EOF
      chmod 600 /root/.eternalfarm/checker.config

      # Create browser automator config to auto-login
      echo "ðŸ“ Creating EternalFarm Browser Automator auto-login config..."
      cat > /root/.eternalfarm/browser-automator.config << EOF
      {
        "key_path": "/appdata/EternalFarm/api.key",
        "remember_key": true,
        "auto_login": true
      }
      EOF
      chmod 600 /root/.eternalfarm/browser-automator.config

      # Update desktop shortcuts to use the auto-login
      echo "ðŸ–¥ï¸ Updating desktop shortcuts..."

      # Update EternalFarm Agent desktop shortcut
      cat > /root/Desktop/EternalFarm-Agent.desktop << EOF
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=EternalFarm Agent
      Comment=EternalFarm Agent Application
      Exec=xfce4-terminal --hold --title='EternalFarm Agent' --command='/usr/local/bin/EternalFarmAgent --auto-login --key-file=/appdata/EternalFarm/agent.key --show-gui'
      Icon=utilities-terminal
      Terminal=false
      Categories=Utility;
      EOF

      # Update EternalFarm Checker desktop shortcut
      cat > /root/Desktop/EternalFarm-Checker.desktop << EOF
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=EternalFarm Checker
      Comment=EternalFarm Checker Application
      Exec=xfce4-terminal --hold --title='EternalFarm Checker' --command='/usr/local/bin/EternalFarmChecker --auto-login --key-file=/appdata/EternalFarm/checker.key --show-gui'
      Icon=utilities-terminal
      Terminal=false
      Categories=Utility;
      EOF

      # Update EternalFarm Browser Automator desktop shortcut
      cat > /root/Desktop/EternalFarm-Automator.desktop << EOF
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=EternalFarm Browser Automator
      Comment=EternalFarm Browser Automator Application
      Exec=xfce4-terminal --hold --title='EternalFarm Browser Automator' --command='/usr/local/bin/EternalFarmBrowserAutomator --auto-login --key-file=/appdata/EternalFarm/api.key --show-gui'
      Icon=utilities-terminal
      Terminal=false
      Categories=Utility;
      EOF

      # Make desktop files executable
      chmod +x /root/Desktop/*.desktop

      # Ensure all keys exist and have content
      echo "ðŸ”‘ Checking EternalFarm keys..."
      AGENT_KEY="${AGENT_KEY:-${ETERNALFARM_AGENT_KEY:-${API_KEY:-}}}"
      CHECKER_KEY="${CHECKER_KEY:-${ETERNALFARM_AGENT_KEY:-${API_KEY:-}}}"
      AUTOMATOR_KEY="${AUTOMATOR_KEY:-${ETERNALFARM_AGENT_KEY:-${API_KEY:-}}}"

      echo "${AGENT_KEY}" > /appdata/EternalFarm/agent.key
      echo "${CHECKER_KEY}" > /appdata/EternalFarm/checker.key
      echo "${AUTOMATOR_KEY}" > /appdata/EternalFarm/api.key

      chmod 600 /appdata/EternalFarm/agent.key
      chmod 600 /appdata/EternalFarm/checker.key
      chmod 600 /appdata/EternalFarm/api.key

      # Echo status
      echo "âœ… Auto-login fix completed"
      echo "==================================================="
      echo "The following files have been updated:"
      echo "  - /appdata/DreamBot/BotData/settings.json"
      echo "  - /root/.eternalfarm/agent.config"
      echo "  - /root/.eternalfarm/checker.config" 
      echo "  - /root/.eternalfarm/browser-automator.config"
      echo "  - Desktop shortcuts updated with auto-login parameter"
      echo ""
      echo "Please restart the EternalFarm applications and DreamBot client"

      exit 0 