version: '3.8'

services:
  farm-admin:
    image: supscotty/farmboy:latest
    ports:
      - "5900:5900"   # VNC Server
      - "8080:8080"   # noVNC Web Client
      - "3333:3333"   # Farm Manager Web Interface
      - "2222:22"     # SSH Access
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=mysql://farmboy:Sntioi004!@mariadb:3306/farmboy_db
      # API Key for EternalFarm services - REPLACE WITH YOUR KEY
      - API_KEY=YOUR_API_KEY_HERE
      - ETERNALFARM_AGENT_KEY=YOUR_API_KEY_HERE
      # DreamBot Configuration (if using DreamBot)
      - DREAMBOT_USERNAME=YOUR_DREAMBOT_USERNAME
      - DREAMBOT_PASSWORD=YOUR_DREAMBOT_PASSWORD
      # Discord Webhook (optional)
      - DISCORD_WEBHOOK_URL=YOUR_DISCORD_WEBHOOK_URL
      # Display settings for VNC
      - DISPLAY=:1
      # Database Configuration
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
    volumes:
      - farm_data:/app/data
      - dreambot_data:/root/DreamBot
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - farm-network
    labels:
      - "com.farmboy.type=hybrid"
      - "com.farmboy.version=0.2"
      - "com.farmboy.environment=production"
      - "com.farmboy.maintainer=SupScotty"
      # Service Labels
      - "com.farmboy.service.vnc=enabled"
      - "com.farmboy.service.novnc=enabled"
      - "com.farmboy.service.ssh=enabled"
      - "com.farmboy.service.web=enabled"
      # Port Labels
      - "com.farmboy.ports.vnc=5900"
      - "com.farmboy.ports.novnc=8080"
      - "com.farmboy.ports.web=3333"
      - "com.farmboy.ports.ssh=2222"
      # Integration Labels
      - "com.farmboy.integration.dreambot=enabled"
      - "com.farmboy.integration.eternalfarm=enabled"
      - "com.farmboy.integration.discord=enabled"
      # Resource Labels
      - "com.farmboy.resources.memory=2g"
      - "com.farmboy.resources.cpus=2"
      # Database Labels
      - "com.farmboy.database.type=mariadb"
      - "com.farmboy.database.user=farmboy"
      - "com.farmboy.database.host=mariadb"
      - "com.farmboy.database.port=3306"
      - "com.farmboy.database.name=farmboy_db"
      # EternalFarm Service Labels
      - "com.farmboy.eternalfarm.agent.enabled=true"
      - "com.farmboy.eternalfarm.checker.enabled=true"
      - "com.farmboy.eternalfarm.automator.enabled=true"
      - "com.farmboy.eternalfarm.keys.type=individual"
      - "com.farmboy.eternalfarm.services=agent,checker,automator"
      # Auto-login Labels
      - "com.farmboy.autologin=enabled"
      - "com.farmboy.autologin.version=1.0"
      - "com.farmboy.autologin.services=dreambot,agent,checker,automator"

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - TZ=Etc/UTC
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
      - MYSQL_ROOT_HOST=%
    volumes:
      - mariadb_data:/config
      # Comment out problematic mounts for Portainer deployment
      # - ./prisma:/prisma
      # - ./setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pSntioi004!"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s
    networks:
      - farm-network
    labels:
      # Core Database Labels
      - "com.farmboy.database.service=mariadb"
      - "com.farmboy.database.type=mariadb"
      - "com.farmboy.database.version=latest"
      - "com.farmboy.database.provider=linuxserver.io"
      # Configuration Labels
      - "com.farmboy.database.root_host=%" 
      - "com.farmboy.database.default_user=farmboy"
      - "com.farmboy.database.default_db=farmboy_db"
      - "com.farmboy.database.charset=utf8mb4"
      - "com.farmboy.database.collation=utf8mb4_unicode_ci"
      # Security Labels
      - "com.farmboy.database.auth_method=mysql_native_password"
      - "com.farmboy.database.secure_user=farmboy"
      # Health Labels
      - "com.farmboy.database.healthcheck=enabled"
      - "com.farmboy.database.healthcheck.interval=30s"

volumes:
  farm_data:
  dreambot_data:
  mariadb_data:

networks:
  farm-network:
    driver: bridge 