version: '3.8'

services:
  farm-admin:
    image: supscotty/farmboy:latest
    ports:
      - "5900:5900"   # VNC Server
      - "8080:8080"   # noVNC Web Client
      - "3333:3333"   # Farm Manager Web Interface
      - "2222:22"     # SSH Access
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=mysql://farmboy:Sntioi004!@mariadb:3306/farmboy_db
      - API_KEY=RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5
      - ETERNALFARM_AGENT_KEY=RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5
      - ETERNAL_API_URL=https://api.eternalfarm.net
      - ETERNAL_FARM_KEY=${ETERNAL_FARM_KEY:-}
      - ETERNAL_AUTH_KEY=${ETERNAL_AUTH_KEY:-}
      - DISPLAY=:1
      - JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
      # DreamBot Configuration for Bot Launching
      - DREAMBOT_USERNAME=${DREAMBOT_USERNAME:-}
      - DREAMBOT_PASSWORD=${DREAMBOT_PASSWORD:-}
      - DREAMBOT_SCRIPT=${DREAMBOT_SCRIPT:-}
      - DREAMBOT_WORLD=${DREAMBOT_WORLD:-301}
      - DREAMBOT_ARGS=${DREAMBOT_ARGS:---no-splash --developer-mode}
      - DREAMBOT_DIR=/root/DreamBot/BotData
      - DREAMBOT_CLIENT_URL=https://dreambot.org/DBLauncher.jar
      # Legacy DreamBot variables (for backward compatibility)
      - DREAMBOT_USER=${DREAMBOT_USER:-}
      - DREAMBOT_PASS=${DREAMBOT_PASS:-}
      # Proxy Configuration
      - PROXY_HOST=${PROXY_HOST:-}
      - PROXY_PORT=${PROXY_PORT:-}
      - PROXY_USER=${PROXY_USER:-}
      - PROXY_PASS=${PROXY_PASS:-}
    volumes:
      - farm_data:/app/data
      - dreambot_data:/root/DreamBot
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - farm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.farm-admin.rule=Host(`farm-admin.local`)"
      - "traefik.http.services.farm-admin.loadbalancer.server.port=3333"
      # Farm Manager Labels
      - "farm.manager.version=v0.1"
      - "farm.manager.features=bot-launching,vnc,discord,eternalfarm"
      - "farm.manager.description=Farm Manager with DreamBot Launching"
      - "farm.manager.ports.web=3333"
      - "farm.manager.ports.vnc=5900"
      - "farm.manager.ports.novnc=8080"
      - "farm.manager.ports.ssh=2222"

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - TZ=Etc/UTC
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
    volumes:
      - mariadb_data:/config
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - farm-network

volumes:
  farm_data:
  dreambot_data:
  mariadb_data:

networks:
  farm-network:
    driver: bridge 